name: Generate ATT&CK Data

on:
  schedule:
    - cron: "0 3 1,15 * *"
  push:
    branches:
      - main
      - inf-2141-github-actions-oidc-role

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r requirements.txt
#     - name: Generate ATTCK Data
#       env:
#         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#         python run.py
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::265337873895:role/pyattck
        aws-region: us-west-2
    - name: Upload files to S3 with AWS CLI
      run: |
        aws s3 cp generated_attck_data.json s3://${{ secrets.SWIMLANE_PYATTCK_AWS_BUCKET_NAME }} --acl public-read
        aws s3 cp attck_to_nist_controls.json s3://${{ secrets.SWIMLANE_PYATTCK_AWS_BUCKET_NAME }} --acl public-read
